### ISSUE TITLE
BUG: combine PDFs failing

### ISSUE THREAD

**Issue by krpaulson** [ihmeuw-demographics/demUtils#23]
**Describe the bug**
The `combine_pdfs` function is crashing a rstudio IDE on our singularity image, and, failing and producing an error when submitted as a job.

**To Reproduce**
```
library(demUtils)

test <- plot(x = 1:10, y = 1:10)
test2 <- plot(x = 1:100, y = 1:100)

pdf("~/test.pdf")
print(test)
dev.off()

pdf("~/test2.pdf")
print(test2)
dev.off()

input_paths <- c("~/test.pdf", "~/test2.pdf")
output_path <- "~/test_combined.pdf"

demUtils::combine_pdfs(input_paths, output_path)
```

**Expected behavior**
Function writes combined PDF to output path without error.

**Screenshots**
From error log:
```
Traceback (most recent call last):
  File "/{redacted path for IHME Rstudio singularity images}/container_cache.py", line 164, in <module>
    filepath = sys.argv[1]
IndexError: list index out of range
FATAL:   image format not recognized
```

**Desktop (please complete the following information):**
 - Singularity version `v2020.0.8`

**Additional context**
To qsub, I put this at the top of my script with the test code above:
```
if(interactive()) {
  demInternal::qsub(
    jobname = "test",
    code = "~/testing_combine_pdfs.R",
    shell = "/{path to demographics team shells}/exec.sh",
    fthread = 5,
    fmem = 20,
    h_rt = "01:00:00",
    archive = T,
    pass_argparse = list(),
    submit = T
  )
}
```

I haven't tested this, but I'd be curious to know if the python code is working and it's just the R wrapper that is failing.

**Comment by krpaulson** [comment]
@chacalle tagging you so that you are aware.

**Comment by chacalle** [comment]
I used this example code on `v2020.0.9`

```
library(demUtils)
library(ggplot2)
library(data.table)

test_dt <- data.table(x = 1:10, y = 1:10)
test_dt2 <- data.table(x = 1:100, y = 1:100)

test_plot <- ggplot(test_dt, aes(x = x, y = y)) + geom_point()
test_plot2 <- ggplot(test_dt2, aes(x = x, y = y)) + geom_point()

pdf("~/test.pdf")
print(test_plot)
dev.off()

pdf("~/test2.pdf")
print(test_plot2)
dev.off()

input_paths <- c("~/test.pdf", "~/test2.pdf")
output_path <- "~/test_combined.pdf"

demUtils::combine_pdfs(input_paths, output_path)
```
which gives the error
```
> demUtils::combine_pdfs(input_paths, output_path)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  FileNotFoundError: [Errno 2] No such file or directory: '~/test_combined.pdf'

Detailed traceback: 
  File "<string>", line 24, in combine_pdfs_py
  File "//usr/local/lib/python3.7/dist-packages/PyPDF2/merger.py", line 214, in write
    fileobj = file(fileobj, 'wb')
Called from: py_call_impl(callable, dots$args, dots$keywords)
```

**Comment by chacalle** [comment]
Even though the file exists, within python it seems to not be finding it. Replacing the `~` with the home directory seems to solve the issue. Will update the function to do this automatically.

```
library(demUtils)
library(ggplot2)
library(data.table)

test_dt <- data.table(x = 1:10, y = 1:10)
test_dt2 <- data.table(x = 1:100, y = 1:100)

test_plot <- ggplot(test_dt, aes(x = x, y = y)) + geom_point()
test_plot2 <- ggplot(test_dt2, aes(x = x, y = y)) + geom_point()

pdf(fs::path_expand("~/test.pdf"))
print(test_plot)
dev.off()

pdf(fs::path_expand("~/test2.pdf"))
print(test_plot2)
dev.off()

input_paths <- c(fs::path_expand("~/test.pdf"), fs::path_expand("~/test2.pdf"))
output_path <- fs::path_expand("~/test_combined.pdf")

demUtils::combine_pdfs(input_paths, output_path)
```
